### ISSUE TITLE
Monitor NSM load

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#101]
Monitor NSM load: it should add extra NSM hosts/clusters as soon as 50 namespaces are created on that host/cluster.

A starting point: https://github.com/openvstorage/framework-alba-plugin/blob/master/ovs/lib/albacontroller.py#L1622

**Comment by jeroenmaelbrancke** [comment]
issue can be closed: https://github.com/openvstorage/openvstorage-monitoring/issues/86

**Comment by JeffreyDevloo** [comment]
@wimpers What type of check would you need in the healthcheck?

**Comment by wimpers** [comment]
Please check if above set max capacity.

**Comment by matthiasdeblock** [comment]
Check_MK already has such a check to monitor the MDS load, the code can perhaps be used. You can find it here: https://github.com/openvstorage/openvstorage-monitoring/blob/master/roles/check_mk_agent/files/clientside/nsm_checkup

I assume the healthcheck won't create any extra arakoons as it is not a tool that fixes issues?

**Comment by wimpers** [comment]
> I assume the healthcheck won't create any extra arakoons as it is not a tool that fixes issues?

It shouldn't create additional arakoons

**Comment by JeffreyDevloo** [comment]
Part of the next 3.4 release

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.2
