### ISSUE TITLE
logger.print_progress not working

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#112]
The 'if not logger.print_progress' is not working.

https://github.com/openvstorage/openvstorage-health-check/blob/fargo/ovs/extensions/healthcheck/arakoon/arakooncluster_health_check.py#L275

for example:
ovs healthcheck
```
[INFO] Try 1 on cluster 'voldrv'
[SUCCESS] ALL available Arakoon(s) their integrity are/is OK! 
[SUCCESS] ALL Arakoon(s) restart check(s) is/are OK!
[FAILED] 2 Arakoon(s) having issues with collapsing: ovsdb,voldrv
[INFO] Starting Alba Health Check!
[INFO] ===========================

```
The failed check showed before extra information about the oldest file

previous output:
```
[FAILURE] oldest file: 000.tlx with timestamp: 2016-08-08T19:09:50.898199 is older than 2016-08-17T00:00:00 for arakoon hdd_roub_nsm_2
[FAILURE] oldest file: 000.tlx with timestamp: 2016-08-08T19:09:45.642235 is older than 2016-08-17T00:00:00 for arakoon hdd_roub_nsm_1
[FAILURE] oldest file: 000.tlx with timestamp: 2016-08-08T19:24:08.872410 is older than 2016-08-17T00:00:00 for arakoon flash_roub_nsm_1
[FAILURE] 3 Arakoon(s) having issues with collapsing: hdd_roub_nsm_2,hdd_roub_nsm_1,flash_roub_nsm_1
```

**Comment by JeffreyDevloo** [comment]
Since the output that was expected is for attended install, the solution is removing the 'not' within the check.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/120, packages in penvstorage-health-check-3.1.2_rev.176.0a97c0e-1.x86_64 / openvstorage-health-check-3.1.2_fargo.3-1.x86_64
