### ISSUE TITLE
Add check for RDMA, enabled/capable

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#116]
We've had some issues that some customers enable RDMA on their systems but its not installed. 
We should detect in the model that RDMA is enabled vs. if RDMA cards are usable/installed.

**Comment by JeffreyDevloo** [comment]
I suspect the framework to already have this check.
The RDMA enabled ball in the storagerouter page is green when the hardware is actually installed.

**Comment by wimpers** [comment]
RDMA is out of the picture. If needed re-open.
