### ISSUE TITLE
Adding tasks for every module who grep in the log files for common errors

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#164]
## Feature description
We currently have 4 modules, for the arakoon module we are already checking if arakoon is restarting to quickly or not. In the future we could add some more tasks in the other modules who do this too.

### Setup
- [x] Hyperconverged
- [x] Hyperscale
- [x] Geoscale

**Comment by kinvaris** [comment]
https://github.com/openvstorage/openvstorage-health-check/issues/78

**Comment by wimpers** [comment]
Let's think this through before we engage in this as this gave us a lot of trouble in case of SSO.  We now also have the central log analyser which we can easily update.

**Comment by JeffreyDevloo** [comment]
The arakoon restart-check was a very basic implementation and did not check all possible cases.
We can use https://github.com/openvstorage/framework/pull/1250 to possible implement it but this test would mean a lot of overhead.

**Comment by JeffreyDevloo** [comment]
After checking with @jeroenmaelbrancke this check would require too much resource for the healthcheck and should frankly be monitored by Ops.
