### ISSUE TITLE
Implement level based healthchecking

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#165]
### Description
Implement level based healthchecking. The most critical components need to be in level 1, less critical components level 2, ...

### How to implement
Currently we have the possibility to run tasks seperately as displayed in `ovs healthcheck help`
```
root@ctrl-roub-02:~# ovs healthcheck help
Possible options are: 
ovs healthcheck volumedriver check_dtl
ovs healthcheck volumedriver check-volumedrivers
ovs healthcheck volumedriver test
ovs healthcheck ovs filedrivers-test
ovs healthcheck ovs halted-volumes-test
ovs healthcheck ovs dns-test
ovs healthcheck ovs model-test
ovs healthcheck ovs packages-test
ovs healthcheck ovs processes-test
ovs healthcheck ovs ovs-workers-test
ovs healthcheck ovs directories-test
ovs healthcheck ovs required-ports-test
ovs healthcheck ovs log-files-test
ovs healthcheck ovs local-settings-test
ovs healthcheck ovs zombie-processes-test
ovs healthcheck ovs test
ovs healthcheck alba backend-test
ovs healthcheck alba proxy-test
ovs healthcheck alba disk-safety
ovs healthcheck alba test
ovs healthcheck arakoon check-arakoons
ovs healthcheck arakoon collapse-test
ovs healthcheck arakoon required-ports-test
ovs healthcheck arakoon restart-test
ovs healthcheck arakoon test
ovs healthcheck arakoon integrity-test
```

We can easily implement level based healthchecking through this functionality and display it in the `help`.

Something like this: `ovs healthcheck level 1`

### Setup
- [x] Hyperconverged
- [x] Hyperscale
- [x] Geoscale

**Comment by wimpers** [comment]
@wimpers please define levels

**Comment by kinvaris** [comment]
@wimpers: Well you could implement levels in the following ways:
* Levels based on critical/urgent/normal/minor
* Levels based on execution time/ execution frequency

**Comment by wimpers** [comment]
Since we currently have the possibility to run tasks separately nothing needs to happen.  People can cherry pick the tests they need and define their own schedule.

**Comment by wimpers** [comment]
Re-open if needed.
