### ISSUE TITLE
Detection of stale FS metadata

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#166]
## Problem description
Last week (and this week as well) we had some issues (GIG) with FS metadata leftovers. That got the volumedriver health check into an ERROR state. Nevertheless the volumedriver was still working but due to the FS metadata leftovers the health check got into ERROR state. 

Due to this ERROR state the SPOC will call BEOPS at night while this isn't something urgent.

## Known problems
* Removing the volumes using the rm -rf command on the fuse interface: https://github.com/openvstorage/openvstorage-health-check/issues/146

## Possible solution
Detection of stale FS metadata when creating a health check volume should be returned as WARNING and not as CRITICAL/ERROR.

**Comment by JeffreyDevloo** [comment]
This has actually been fixed a while back
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/261
