### ISSUE TITLE
Check for dropped messages in the logs

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#171]
See https://github.com/openvstorage/integrationtests/issues/354

we should check in the logs if messages are being dropped and display this as warning.

**Comment by wimpers** [comment]
This will of course only work for journalctl. We can think of a different way for other log targets in a later stage or when needed.

**Comment by wimpers** [comment]
If the changes to the journalctl config are made based upon https://github.com/openvstorage/framework/issues/1227#issuecomment-267539662 this issue is obsolete. 

The rate limit are set to zero with RateLimitInterval and RateLimitBurst being 0. No messages will be dropped this way. Hence proposing to close.

**Comment by JeffreyDevloo** [comment]
The configuration of journald should have fixed the issue (according to man journald.conf)
