### ISSUE TITLE
Checking of ASDs should not only be possible from master nodes

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#177]
This is based on a customer case http://tickets.openvstorage.com/browse/OVSSUP-119 . Customer was running the HC on an extra node which had ASDs inside. I propose that if the HC is executed on a node with the ASD mananger which isn't a master node (extra node or just an ASD node) it also checks the ASDs . It should not check all ASDs in the cluster of course and no backend safety checks should be executed.

**Comment by wimpers** [comment]
This ticket is to make sure the HC can also run on ASD-manager only nodes.  Proposal is to set this on Roadmap.

A short term solution is to make sure the default behaviour on extra nodes is to also test local ASDs. This will be picked up in another ticket.

**Comment by kinvaris** [comment]
So for short-term we will implement the following:
* All the asds will still be checked by master nodes
* Extra nodes will check if they have local asds, if so they will check this.

For long-term as I discussed with @wimpers, we will implement the following:
* master and extra nodes will check if they have local asds, if so they will test them
* dedicated storage nodes with only the asd-manager running on them will only test local asds
