### ISSUE TITLE
Use smartctl to verify health of the disks

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#178]
It might be good to add smartctl to the HC to check the health of the disks. I would add this as an optional flag. based on evidence of [Backblaze](https://www.backblaze.com/blog/hard-drive-smart-stats/) there are at least 5 stats which are good at predicting failures. 

Some remarks:
* This would of course be a warning. 
* This might only be applicable to SATA drives and not to SSDs.

**Comment by domsj** [comment]
My suggestion here would be (as mentioned to @jtorreke earlier): capture the smartctl output for each disk daily, it might be useful some day...

**Comment by wimpers** [comment]
@domsj You are correct. that is why I created https://github.com/openvstorage/openvstorage-health-check/issues/178 as part of the monitoring. This would be a more ad hoc call to check the disk health

**Comment by kinvaris** [comment]
In this case of using smartctl we can only check the local disks of where the healthcheck is running. We would not be able to check disks on storagenodes. Shouldn't this be for monitoring and not for the healthcheck?

**Comment by kinvaris** [comment]
@wimpers : why does this also need to be implemented in the healtcheck as the monitoring will support this?

**Comment by wimpers** [comment]
At the moment the view is that the healthchceck should check our software components and nothing hardware related or (non-ovs) disk full scenario's. This one should be tackled only in monitoring. We will re-open if needed.
