### ISSUE TITLE
ovs healthcheck must be able to run as asd-manager healthcheck

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#181]
For long-term we will implement the following:

* master and extra nodes will check if they have local asds, if so they will test them
* dedicated storage nodes with only the asd-manager running on them will only test local asds: asd-manager healthcheck

**Comment by wimpers** [comment]
Can we try to pick this up asap  (even try to squeeze it into RC2?)

**Comment by JeffreyDevloo** [comment]
We are currently testing all asds within the cluster from a single master node at any given time.
I do not know why we would have to spread this out anymore.

@wimpers 
Any input?

**Comment by wimpers** [comment]
No longer required. if the need would rise again, re-open this ticket. or create a new one.
