### ISSUE TITLE
Detect (and prevent) 2 healthchecks are running at the same time

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#184]
This is a follow up ticket on https://github.com/openvstorage/openvstorage-health-check/issues/146 . As a first step during the healthcheck it would be a good idea that the healthcheck checks if there is already another healthcheck ongoing.

**Comment by JeffreyDevloo** [comment]
Are you referring to multiple instances of healtchecks running on the same node? There should be a lock for that indeed.
Multiple instances running in a cluster on seperate nodes should not be problem.

**Comment by wimpers** [comment]
multiple instances of healtchecks running on the same node

**Comment by wimpers** [comment]
protect on running the healthcheck on the same node

**Comment by JeffreyDevloo** [comment]
Will use filemutex to lock execution to one at the time.

**Comment by kinvaris** [comment]
@JeffreyDevloo because we are working with the api we choose for `volatile_mutex`

**Comment by JeffreyDevloo** [comment]
So you are locking the healthcheck, which checks its own system, to run only once at a time on a cluster?

**Comment by kinvaris** [comment]
@JeffreyDevloo no we've observed the components that could cause problems when running 2 healthchecks at a time. Those components have been adjusted to create lock so other healthchecks don't interfere.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/198
