### ISSUE TITLE
Add fixed codes to each check

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/openvstorage-health-check#196]
The plan exists to build a knowledge base to make customers more self-preserving. One tool they can use to do so is the health check. For each check a code should be added so we can uniquely identify each check and add a possible solution to the knowledge base if failed - independent from the description.
The tag/code itself is up to you, but chose something and stick with it as we'll base our entire documentation on this. Some examples:

* HC-0001, HC-0002, HC-0003, ...
* HC-ALBA-0001, HC-VOLDRV-0008, HC-FWRK-0048, ...

If you should have any questions, please shoot.

**Comment by JeffreyDevloo** [comment]
@jtorreke 
I suppose that these codes should remain unchanged for every future iteration of the healthcheck?

**Comment by jtorreke** [comment]
@JeffreyDevloo Correct. That's the idea behind the fixed codes. Or we would have to revamp documentation every time a check is added.

**Comment by kinvaris** [comment]
@JeffreyDevloo we could write a decorator who makes it fairly easy to add this to the existing methods.

**Comment by wimpers** [comment]
@JeffreyDevloo What is the status of this? Is this much work?

**Comment by JeffreyDevloo** [comment]
We only require a database of codes now.
