### ISSUE TITLE
Separating the BACKEND test from the FRAMEWORK test.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#22]
On request we considered the separation of the FRAMEWORK test from the BACKEND test because:
When 1 ASD breaks, all the nodes (MASTER + EXTRA) give errors. 

We considered to run 2 healthchecks: on compute nodes and on storage nodes.
But this will not work due to the fact the the storage nodes in hyperscale do not contain libraries from Open vStorage itself (compared with hyperconverged). 

We have come to the decision that we will not seperate the BACKEND check but we will:
- Execute the FRAMEWORK+BACKEND test on all MASTER nodes (So the backend test will only run on 3 - 5 - 7 - .. nodes; dependent on how many MASTER nodes you have.)
- We will still execute the healthcheck on the EXTRA nodes but it will ONLY be a FRAMEWORK test. 

So when a ASD fails you won't have problems on "all" your nodes pointed out from the perspective of the healthcheck.

**Comment by kinvaris** [comment]
Alba and other tests will probably run only on MASTER nodes

**Comment by wimpers** [comment]
@kinvaris is this ticket still relevant? Who (which customer) requires this?

**Comment by kinvaris** [comment]
@wimpers: this ticket was already fixed a few months ago. So this can be closed
