### ISSUE TITLE
Add version of the health check to the output

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#232]
Please add the version nr of the healthchceck to this output so people can easily see in which version of the healthchceck the issue is noticed

```root@pocops-ovs03:~# ovs healthcheck
[INFO] Starting Open vStorage Health Check!
[INFO] ====================================
[INFO] Fetching LOCAL information of node:
[INFO] Cluster ID: 43uDizr0NrXgcG0B
[INFO] Hostname: pocops-ovs03
[INFO] Storagerouter ID: YqqWtzEv5EFUq5fa
[INFO] Storagerouter TYPE: MASTER
[INFO] Environment RELEASE: Fargo
[INFO] Environment BRANCH: Fargo
[INFO] Environment OS: Ubuntu 16.04.1 LTS
[SUCCESS] Fetched all local settings
[INFO] Checking LOCAL OVS services:

```

**Comment by wimpers** [comment]
Seems it is already picked up 

[SUCCESS] Package openvstorage-health-check is present, with version 3.1.5-fargo.1-1

Add the packages at the top

**Comment by JeffreyDevloo** [comment]
The line 'Starting Open vStorage Health Check!' could have the version in it to easily distinguish it.
