### ISSUE TITLE
Split up cluster wide checks from node specific checks

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#236]
Currently all master nodes are running cluster wide checks which means we test items multiple times. 
A better approach would be to split up the cluster wide  and node specific checks. This way we can call the cluster wide check once for the cluster and the node specific check can run on the individual nodes.

**Comment by wimpers** [comment]
@JeffreyDevloo @khenderick would it make sense to add the clusterwide checks in the framework and expose the results through cli/API and  have health check use the api/cli? i see this as a possible first step in  https://github.com/openvstorage/home/issues/47

**Comment by JeffreyDevloo** [comment]
@wimpers That could be a possibility but for that the fwk team should have owner of the whole healthcheck and could implement everything we have so far an API afaik.
However the way the ticket you linked is mainly that other components can be checked with simple APIs, not the framework orchestrating the current healthcheck

Either way. Another remark is that Ops their CheckMK requires all nodes to report something of output, even if they should not run the cluster wide checks. This means that the HC itself cannot schedule the test to be ran on node X but should run a dummy code that just logs something (preferably who actually executed the check) on other nodes than X.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/288
