### ISSUE TITLE
Output of healthcheck - json

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#237]
Output should have 2 types of output:
* human readable (default)
* json format (e.g. --to-json  like alba)

Note: unattended can be removed.

**Comment by wimpers** [comment]
@grimpy might be useful for you guys too

**Comment by JeffreyDevloo** [comment]
What to rework:
- All tests should be bundled under one test name
- No test should fail when a single component fails
- A detailed message should be provided within the json dict of what went wrong during testing

Code wise:
- [ ] Rework current logging (only use for attended)
- [ ] Add result parser
- [ ] Filter out the possible modes and put them under one general method
