### ISSUE TITLE
Review the level for each health check test

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#238]
Review the level for each health check test based upon what check mk can do. Suggested levels warning (default), error (in case you want to be called out of bed)

Add below which tests should report an error or if  a test needs to be changed.

**Comment by wimpers** [comment]
@matthiasdeblock  any update on this? Did you provide input to @JeffreyDevloo ?

**Comment by matthiasdeblock** [comment]
@wimpers we are waiting for some changes which are in progress (json, extra subdivision ...). There are too many changes for now. Also, @JeffreyDevloo will set everything to WARNING except when he is 100% sure that OVS will be down.

https://github.com/openvstorage/openvstorage-health-check/issues/249
https://github.com/openvstorage/openvstorage-health-check/issues/237
...
