### ISSUE TITLE
Check if a recovery domain is set as primary domain

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#258]
In https://github.com/openvstorage/framework/issues/600#issuecomment-272479195 it was decided that we would not block setting a reocery domain if it isn't set as a primary domain. 

The health check should notify that  a domain is set as recovery domain when it isn't set anywhere as primary domain.  The alert should be warning.

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.5 release
