### ISSUE TITLE
Fetching LOCAL information of node should be on top of the `ovs healthcheck`

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#266]
Referring to this information when running the healthcheck:
```
[INFO] Fetching LOCAL information of node: 
[INFO] Storagerouter Type: MASTER
[INFO] Environment Os: Ubuntu 16.04.1 LTS
[INFO] Environment Release: Fargo
[INFO] Hostname: ovs-node01-1604
[INFO] Environment Branch: Unstable
[INFO] Storagerouter Id: ODeL4zW5hnud6QUk
[INFO] Cluster Id: LrPUI5U9IRdkKUgM
```

This information should always be on top when executing `ovs healthcheck`

**Comment by JeffreyDevloo** [comment]
Too be honest. I dont think this should still be a check. It should just add some more information to the healthcheck.

**Comment by kinvaris** [comment]
@JeffreyDevloo sure, I don't mind that this is not internally qualified as a test, and just give as info. It just needs to be displayed at the top of the output

**Comment by JeffreyDevloo** [comment]
root@ovs-node01-1604:~# ovs healthcheck
[INFO] Storagerouter Type: MASTER
[INFO] Environment Os: Ubuntu 16.04 xenial
[INFO] Environment Release: Fargo
[INFO] Hostname: ovs-node01-1604
[INFO] Environment Branch: Unstable
[INFO] Storagerouter Id: EtmwTmK7hcOZ9CU9
[INFO] Cluster Id: SE8Tz5n3pFXldQ9o
[INFO] Starting OpenvStorage Healthcheck version 3.1.5-rev.443.cf8353b-1
[INFO] ======================
