### ISSUE TITLE
healthcheck never ends when checks are waiting on memcache

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#28]
Best solution is to use a timeout frame when the check is waiting on memcache.

**Comment by kinvaris** [comment]
Agreed, but what if memcache crashes after a check on memcache? You can't time out everyting in a script.

**Comment by kinvaris** [comment]
Will implement a more effecient timout system: https://pypi.python.org/pypi/timeout-decorator

**Comment by JeffreyDevloo** [comment]
No longer occurred for a real while now. Never seen it myself therefore closing it down.
