### ISSUE TITLE
Clarify volume state description

### ISSUE THREAD

**Issue by redlicha** [openvstorage/openvstorage-health-check#283]
Healthcheck reports volumes as "halted" if they're not running (failed to restart, e.g. problem during startup or migration). VolumeDriver volumes do however have a "halted" state which is different from that: the volume is actually started up but refuses any further I/O due to some "catastrophic" event, e.g. fencing preventing a volume from writing to the backend because HA started another instance of the volume on a different volumedriver.

**Comment by kinvaris** [comment]
We are using the properly `halted` in the volume information, to what property are you referring @redlicha

**Comment by redlicha** [comment]
And that's the correct use of it. This ticket was triggered by reports of volumes as "HALTED" that were however not halted in the above sense but not restarted, based on this conversation:

> [10:08:57] Matthias De Block: Healthcheck output for G8-4:
> [FAILED] Detected volumes that are HALTED in vPool data04: a5ca8b83-20ee-458c-b882-06f20ac0f057, f403bf6b-2b36-480b-802e-03a113609a61
> [10:10:07] Arne Redlich: "a5ca8b83-20ee-458c-b882-06f20ac0f057" is the one that fails to start up on stor-03
> [10:10:41] Arne Redlich: also, what does "halted" mean in healthcheck lingo? volume in "halted" state, or failed to restart?
> [10:10:54] Jeffrey Devloo: not running while it should
> [10:11:17] Arne Redlich: so not (re)started

**Comment by wimpers** [comment]
@JeffreyDevloo  When does the HC report HALTED?

**Comment by JeffreyDevloo** [comment]
Call to determine it :if int(VolumedriverHealthCheck._info_volume(voldrv_client, volume).halted):

**Comment by JeffreyDevloo** [comment]
So we actually just check whether the volume is halted.
