### ISSUE TITLE
Namespace fails to create because it already exists

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#287]
## Problem description
```
CRIT - FAILED HC000 - Create namespace has failed with Command proxy-create-namespace failed with Proxy exception: Proxy_protocol.Protocol.Error.NamespaceAlreadyExists. on namespace ovs-healthcheck-ns-hddPreset with proxy albaproxy_vpool01_1 with preset hddPreset
```

## Possible root of the problem

* Possibility that cluster wide mutex does not work
* The code has a mistake in it

**Comment by JeffreyDevloo** [comment]
This and https://github.com/openvstorage/openvstorage-health-check/issues/286 are related in some way.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/288
