### ISSUE TITLE
Check health of volumedriver's SCO cache mount points

### ISSUE THREAD

**Issue by redlicha** [openvstorage/openvstorage-health-check#289]
The forthcoming voldrv release will have a new `sco_cache_mount_point_info` call in its Python API which allows to query the `offlined` state (amongst other attributes) of a voldrv's SCO cache mount points - https://github.com/openvstorage/volumedriver/issues/278
.

**Comment by JeffreyDevloo** [comment]
@redlicha Could you elaborate a bit more on how you see the implementation? What states should we look out for to log our warnings / errors

**Comment by redlicha** [comment]
As mentioned in the original description, the `offlined` attribute should be monitored. By way of example:
```
In [7]: import volumedriver.storagerouter.storagerouterclient as src

In [8]: client = src.LocalStorageRouterClient("/tmp/RemoteTest/remote/volumedriverfs.json")

In [9]: [ (i.path,i.offlined) for i in client.sco_cache_mount_point_info("node_0") ]
Out[9]: [('/tmp/RemoteTest/scache/0', False)]
```
Other available attributes:
```
In [10]: src.SCOCacheMountPointInfo.
src.SCOCacheMountPointInfo.capacity  src.SCOCacheMountPointInfo.free      src.SCOCacheMountPointInfo.offlined  src.SCOCacheMountPointInfo.used      
src.SCOCacheMountPointInfo.choking   src.SCOCacheMountPointInfo.mro       src.SCOCacheMountPointInfo.path      
```

**Comment by simonOpenV** [comment]
fixed in #397 
package info: openvstorage-health-check-3.6.2-dev.1513258399.a420835

**Comment by wimpers** [comment]
@simonOpenV should this one be closed or set to code complete?

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.5 release
