### ISSUE TITLE
Take a volumedriver's "volume potential" into account

### ISSUE THREAD

**Issue by redlicha** [openvstorage/openvstorage-health-check#293]
VolumeDriver instances have a "volume potential" which indicates how many more volumes it can host (newly created / migrated to it). If that reaches 0, creation of new volumes is refused, which is something the healthcheck might stumble over. The volume potential of a voldrv instance can be retrieved via the Python API:

```
In [1]: import volumedriver.storagerouter.storagerouterclient as src

In [2]: client = src.LocalStorageRouterClient("/tmp/RemoteTest/remote/volumedriverfs.json")

In [3]: client.volume_potential("node_0")
Out[3]: 9

```

**Comment by wimpers** [comment]
@JeffreyDevloo  currently the HC no longer creates volumes right?

**Comment by wimpers** [comment]
Maybe a better solution would be to expose this in the framework so statistics/grafana can check and report on it?

Framework could also use it to not show storage routers  on which volumes can be created. Users could also query this api to get a list of nodes and hence decide where best create a vdisk. @khenderick wdyt ?

**Comment by khenderick** [comment]
@wimpers, that's possible

**Comment by JeffreyDevloo** [comment]
@wimpers 
Yes the healthcheck has currnetly disabled the volume creation.
However no the healthcheck has no feedback from its volumedriver so we need to fix the core issue and this is an enhancement.

**Comment by wimpers** [comment]
Please report volume potential in the healthcheck so monitoring can pick it up.

**Comment by simonOpenV** [comment]
--> http://10.100.129.100:8080/view/Packaging/job/qa-packaging/128/

**Comment by simonOpenV** [comment]
--> a46b13d

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.5 release
