### ISSUE TITLE
Wrong amount of namespaces listed

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#304]
## Problem description
Still an issue with the disk-safety.

Now we receive an ok state with only 1 namespace in the backend.

```
OK - SUCCESS HC000 - All data is safe on backend hddBackend with 1 namespace(s)
```

Check the code and found that you forgot that you add the disk-safety also in the dictionary.
https://github.com/openvstorage/openvstorage-health-check/blob/6de7733b80df441298b7a15588084ee4f053e765/ovs/extensions/healthcheck/alba.py#L420

you need the length from current_disk_safety with index the calculated_disk_safety
https://github.com/openvstorage/openvstorage-health-check/blob/6de7733b80df441298b7a15588084ee4f053e765/ovs/extensions/healthcheck/alba.py#L493

Snippet of the keys and lengths:

```
In [35]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:for backend_name, policies in results.iteritems():
:    for policy_prefix, policy_details in policies.iteritems():
:        print backend_name, policy_prefix, policy_details.keys()
:        print "current_disk_safety length:", len(policy_details['current_disk_safety'])
:        print "current_disk_safety keys:", policy_details['current_disk_safety'].keys()
:        for disk_safety in policy_details['current_disk_safety'].keys():
:            print "calculated_disk_safety:", len(policy_details['current_disk_safety'][disk_safety])
:--
hddBackend 8,2 ['max_disk_safety', 'current_disk_safety']
current_disk_safety length: 1
current_disk_safety keys: [2]
calculated_disk_safety: 563
ssdBackend 4,1 ['max_disk_safety', 'current_disk_safety']
current_disk_safety length: 0
current_disk_safety keys: []

```
Continued from https://github.com/openvstorage/openvstorage-health-check/issues/292

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/306

**Comment by wimpers** [comment]
@JeffreyDevloo please put in the right state (verification, in progress, ...)
