### ISSUE TITLE
Alba proxy test enhancements

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#305]
## Problem description
- Wait for proxy to be fully created
- Wait for proxy to be fully deleted
- Unique name
This will avoid:
- Namespace already exists
- Unsatisfiable policy

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/306

**Comment by wimpers** [comment]
@JeffreyDevloo  any reason why this isn't set to closed/fixed ?
