### ISSUE TITLE
Add unit when logging ... not older than 2, as it's unclear what 2 refers to

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/openvstorage-health-check#307]
## Problem description

arakoon-collapse-test_1d -> WARNING HC000 - Oldest tlx file for Arakoon hddBackend-nsm_9 is not older than 2

It's not clear what 2 refers to ...

**Comment by JeffreyDevloo** [comment]
Already tackled by: https://github.com/openvstorage/openvstorage-health-check/pull/308
No issue was created previously.
