### ISSUE TITLE
Running multiple healthcheck on one server leads to Errors on alba proxy-test

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#310]
## Problem description
Running multiple alba proxy-test on one server leads to errors in the healthcheck.

Scenario:
Running healthcheck with check_mk every 3 minutes.
If someone runs the healthcheck at the same moment the check_mk plugin runs the other check can delete the used namespace in the our check.

for example:
check 1: --> create namespace --> upload object --> verify object --> delete object --> delete namespace
check 2: --> not running            --> create namespace --> error namespace already exists

```
CRIT - FAILED HC000 - Create namespace has failed with Command 'proxy-create-namespace' failed with 'Proxy exception: Proxy_protocol.Protocol.Error.NamespaceAlreadyExists'. on namespace ovs-healthcheck-ns-hddPreset-HdC8QGW6PDxBNgIZ with proxy albaproxy_vpool02_0 with preset hddPreset, HC000 - Uploading the object has failed with Command 'proxy-upload-object' failed with 'Proxy exception: Proxy_protocol.Protocol.Error.NamespaceDoesNotExist'. on namespace ovs-healthcheck-ns-hddPreset-HdC8QGW6PDxBNgIZ with proxy albaproxy_vpool02_1 with preset hddPreset
```

## Possible root of the problem

Same namespace is used for all the checks or there is no lock on the check.

### Logs
```
CRIT - FAILED HC000 - Create namespace has failed with Command 'proxy-create-namespace' failed with 'Proxy exception: Proxy_protocol.Protocol.Error.NamespaceAlreadyExists'. on namespace ovs-healthcheck-ns-hddPreset-HdC8QGW6PDxBNgIZ with proxy albaproxy_vpool02_0 with preset hddPreset, HC000 - Uploading the object has failed with Command 'proxy-upload-object' failed with 'Proxy exception: Proxy_protocol.Protocol.Error.NamespaceDoesNotExist'. on namespace ovs-healthcheck-ns-hddPreset-HdC8QGW6PDxBNgIZ with proxy albaproxy_vpool02_1 with preset hddPreset
```

<---------------------------------------------------------->
## Possible solution

* Use unique namespace per alba proxy (use prefix + timestamp or guid)
* Lock the node. (Only one alba proxy-test at the same time)
* Use alba deliver-messages between create namespace and verify namespace
* Clean up all the namespace with prefix from this proxy. ( if multiple namespaces are removed --> warning)

### Setup
- Hyperscale

### Packages
```
ii  openvstorage                         2.7.10.1-1                      amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                      amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                      amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                      amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                      amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                      amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.2.1-rev.494.92e44aa-1         amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.10.1-1                      amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                      amd64        openvStorage Web Applications
```

**Comment by JeffreyDevloo** [comment]
Might actually lead to a whole array of problems.

**Comment by wimpers** [comment]
Didn't we in a previous ticket made sure that no HC can run concurrently on the same node? See https://github.com/openvstorage/openvstorage-health-check/issues/184

**Comment by JeffreyDevloo** [comment]
Only certain methods were actually locked that would give us issues with concurrency.
The alba one was not the case. There was a volatile mutex there, which was then replaced with a clustercheck which then was removed due to it being a local check.

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/openvstorage-health-check/pull/312
