### ISSUE TITLE
volumedriver halted-volumes-test check for fenced volumes

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#315]
## Problem description
When a volume is moved to another volumedriver (HA) it could be that the volume is halted (fenced) on the old volumedriver.

## Possible solution
Check if the volume is already running on another volumedriver with halted state = True?

**Comment by JeffreyDevloo** [comment]
Related to https://github.com/openvstorage/volumedriver/issues/290
Nothing to do on our side (yet).

**Comment by wimpers** [comment]
@JeffreyDevloo  assigning this one to you - please close after integration into healthcheck.

**Comment by JeffreyDevloo** [comment]
Done by https://github.com/openvstorage/openvstorage-health-check/pull/388
