### ISSUE TITLE
Openvcloud:ovs_healthcheck FAILED

### ISSUE THREAD

**Issue by davshafik** [openvstorage/openvstorage-health-check#32]
although the clusters are working fine but we get this error :-
```
Traceback (most recent call last):
    return True, self.module.action(*args, **kwargs)
~   File "/tmp/jumpscripts/cloudscalers_ovs_healthcheck.py", line 83, in action
    check_openvstorage()
~   File "/tmp/jumpscripts/cloudscalers_ovs_healthcheck.py", line 73, in check_openvstorage
    ovs.checkForHaltedVolumes()
~   File "/opt/OpenvStorage-healthcheck/openvstorage/openvstoragecluster_health_check.py", line 725, in checkForHaltedVolumes
    if int(self.utility.parseXMLtoJSON(voldrv_client.info_volume(volume))
~ MaxRedirectsExceededException: volumeInfo 
```

any thought what make this happen ??

**Comment by lzonneke** [comment]
@wimpers do we have any update on this ticket?

**Comment by wimpers** [comment]
@kinvaris can you check and update?

**Comment by kinvaris** [comment]
This has already been fixed on the stable branch: https://github.com/openvstorage/openvstorage-health-check/tree/ovs-impl, just need to merge it to unstable aka master

**Comment by kinvaris** [comment]
Just to clarify, the ovs-impl branch is plugged into Open vStorage code wise. In the future, the ovs-impl branch will be fully merged to master.
