### ISSUE TITLE
Soft warning for port ranges that are (almost) exhausted

### ISSUE THREAD

**Issue by khenderick** [openvstorage/openvstorage-health-check#320]
Soft warning for port ranges that are (almost) exhausted.

Relates to:
* openvstorage/framework#1553
* openvstorage/dev_ops#59

**Comment by JeffreyDevloo** [comment]
Fixed by: https://github.com/openvstorage/openvstorage-health-check/pull/375
Packaged in: openvstorage-health-check_3.6.1-dev.1509030156.3828a53-1_amd64

**Comment by JeffreyDevloo** [comment]
Part of the https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.5 release
