### ISSUE TITLE
Warning missing EE packages in OSE installation

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#325]
As the OVH setup is a OSE it should not show that there are packages missing from the EE. 

 ```
WARN - WARNING HC000 - Package volumedriver-ee-server is not installed., HC000 - Package volumedriver-ee-base is not installed., HC000 - Package alba-ee is not installed.
```

**Comment by JeffreyDevloo** [comment]
Because of the EE, we can no longer rely on the set of required packages the framework returns.
Will have to change accordingly.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/337
