### ISSUE TITLE
Catch false linked backends

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#332]
## Problem description
Get potential issue in the healthcheck also:
https://github.com/openvstorage/framework/issues/1626

**Comment by JeffreyDevloo** [comment]
Fixed by 
https://github.com/openvstorage/openvstorage-health-check/pull/333

**Comment by wimpers** [comment]
@JeffreyDevloo not quite sure what is fixed. This ticket is still open? Anything left to do on the framework?

**Comment by JeffreyDevloo** [comment]
The PR fixes the issue we have on our side. We will no longer hang on empty lists which we were getting due to the linked ticket.

**Comment by wimpers** [comment]
@JeffreyDevloo in that case please put in status in_progress
