### ISSUE TITLE
Support for Kinetic drives

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#341]
Change the health check so it can support Kinetic chassis and Kinetic disks as ASDs.

To be tackled once we have 
- https://github.com/openvstorage/framework-alba-plugin/issues/415
- https://github.com/openvstorage/framework-alba-plugin/issues/414

**Comment by JeffreyDevloo** [comment]
Not sure if much is to be done. All calls are done using the alba id the osds have, so it should already be implemented
