### ISSUE TITLE
Healthcheck spews untrue timeouts in in proxy-test

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#352]
### Problem description
List-ns-osds will not have all osd states as 'Active' due to unreachable osds causing the healthcheck to spew the timeout when its not needed

### Proposed solution
Check the amount of osds needed to satisfy the preset (which was why we implemented this part) and then continue. If the preset cannot be satisfied -> raise

**Comment by wimpers** [comment]
Duplicate of  https://github.com/openvstorage/openvstorage-health-check/issues/378
