### ISSUE TITLE
HC complains that it cannot create namespaces when an OSD is broken

### ISSUE THREAD

**Issue by jtorreke** [openvstorage/openvstorage-health-check#378]
This is the output the HC reports:

```
[INFO] Checking ALBA proxy albaproxy_data01_1.
[INFO] Deleting namespace ovs-healthcheck-ns-gigPreset-qsjZ10r5Wv2RBwEM_d388c8ed-4625-4323-ab10-e1132fb9d41d.
[SUCCESS] Namespace ovs-healthcheck-ns-gigPreset-qsjZ10r5Wv2RBwEM_d388c8ed-4625-4323-ab10-e1132fb9d41d successfully removed.
No handlers could be found for logger "ovs_extensions.generic.filemutex"
[EXCEPTION] Unhandled exception caught when executing check_if_proxies_work. Got Creation namespace has timed out after 30.0104498863s
```

The HC does an alba list-ns-osds <namespace> upon namespace creation. If not all OSDs are showing ACTIVE, HC raises above warning. So the check will always fail is any OSD is broken in that backend. The ideal solution would be that the satisfiability of the policy is checked for the amount of OSDs returned in the list-ns-osds call and appropriate action is taken.

list-ns-osds output:

```
  (20L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (21L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (22L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (23L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Adding);
  (24L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (25L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (26L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (27L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (28L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
  (29L, Albamgr_protocol.Protocol.Osd.NamespaceLink.Active);
```

Check for more info: https://github.com/openvstorage/openvstorage-health-check/blob/master/ovs/extensions/healthcheck/alba_hc.py#L214

**Comment by JeffreyDevloo** [comment]
As suggested during our discussion: set a percentage of active links before proceeding to avoid these situations.
Could you create PR for this?

**Comment by wimpers** [comment]
Why a percentage and not check if required amount of OSDs are available?

**Comment by domsj** [comment]
Fwiw framework already has the code to check whether a policy is satisfiable, so that could be reused...

**Comment by JeffreyDevloo** [comment]
Part of the next 3.4 release

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.2
