### ISSUE TITLE
Make the halted volumes test more granular

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#384]
Halted volumes  can now be reported for volumes in multiple case:
- volume is halted
- max redirect overflow #340
- timeout
- runtime error
- fenced volumes #315
 - ...

Make this more granular so these individual cases are reported instead of the generic "halted volumes".

**Comment by saelbrec** [comment]
Please complete cases that need to be tested

**Comment by JeffreyDevloo** [comment]
Done by https://github.com/openvstorage/openvstorage-health-check/pull/388
