### ISSUE TITLE
Arakoon healthcheck: detect Arakoon catch-up

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#399]
## Problem description
The current Arakoon test suite does not check whether a node is catching up or not. This might prove useful for monitoring purposes

A way to detect this:
```
root@NY1SRV0001:~# arakoon -config arakoon://config/ovs/arakoon/ny1-hddbackend05-nsm_07/config?ini=%2Fmnt%2Fssd1%2Farakoon%2Fexternal_arakoon_cacc.ini --statistics | grep node_is
node_is: (FLM4OmtPuCivo528,12602921)(hVEIul3TXTpCAWwg,12602921)(54JvUoNRaeDhqqD3,12602921)(wZ4GAcmR2MZl5x7S,12602921)(N0RCG4vXgbP0w8LQ,12602921)}
```
When the numbers after the node id mismatch (allow a difference of 10 or so), the node is behind the the master and should raise a warning/failure
When the number is 0, that node is working in catch-up
When there is a node id missing, the Arakoon is down

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/openvstorage-health-check/issues/324 is in a sense related

**Comment by wimpers** [comment]
I think it would be good to test this as part of the linked ticket. hence closing this one down as duplicate. Re-open if you would disagree.
