### ISSUE TITLE
Error codes for issues

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#402]
Currently only a limited list of tests are tagged with an error code (https://github.com/openvstorage/openvstorage-health-check/blob/master/errorcodes.md). This ticket is to expand that to all tests.

After discussion with @JeffreyDevloo : estimate 1/2 days

**Comment by wimpers** [comment]
Please pick up between soup and potatoes.

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.3 / https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.4.5

**Comment by wimpers** [comment]
Should this ticket be in state_validation?
