### ISSUE TITLE
Allow arguments to be passed to the CLI

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#422]
### Feature description
Certain healthcheck methods are parameterized internally. To connect these variables to the CLI, we'd need something new

**Comment by JeffreyDevloo** [comment]
Coul resolve #421

**Comment by wimpers** [comment]
Can we do the following:
* Store all configurable parameters in the config arakoon as single json. 
* On startup the healthcheck get the config from the config arakoon.

**Comment by wimpers** [comment]
Estimated at 2d.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/447
Packaged in: openvstorage-health-check_3.7.0-dev.1525250711.8ba3b6b-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.7.0
Packaged in openvstorage-health-check_3.7.0-1_amd64.deb
