### ISSUE TITLE
Replace general Exceptions by custom Exceptions

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#43]
Put `exceptions.py` under `openvstorage-health-check/ovs/extensions/healthcheck/utils/`

Example: `https://github.com/openvstorage/framework/blob/master/ovs/dal/exceptions.py`

In-code use example: `https://github.com/openvstorage/framework/blob/master/ovs/dal/performance_test.py#L27`
`https://github.com/openvstorage/framework/blob/master/ovs/dal/performance_test.py#L182`

**Comment by JeffreyDevloo** [comment]
### Information
For specific problems we raise our own exceptions.
These can be found in https://github.com/openvstorage/openvstorage-health-check/blob/master/ovs/extensions/healthcheck/helpers/exceptions.py
