### ISSUE TITLE
HC complains about RabbitMQ & workers

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#432]
On  the Centrilogic env we regularly see the following error being reported by the HC while there are no mentions in the logs of the workers of any issues.

`CRIT - FAILED FWK0202 - The test timed out after 7s! Is RabbitMQ and ovs-workers running?`

I believe this is a false positive in the HC.

**Comment by JeffreyDevloo** [comment]
I do not believe this is a false positive at all.
This indicates that either:
- Memcached did not get the result of the workers
- The workers never executed the task we asked them too within the timeframe
Since there are plenty of workers on almost all environments, I'd assume the first option

**Comment by wimpers** [comment]
This would be solved by the storing the result of the workers in Arakoon, right?

**Comment by JeffreyDevloo** [comment]
If the issue is indeed Memcached not responding at that moment, yes.
Still this is no bug in the healthcheck?

**Comment by wimpers** [comment]
OK, Let's close this one and re-open if the above issues would not have fixed that.
