### ISSUE TITLE
Map error condition of the volumedriver to Unknown 

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#438]
Map error condition of the volumedriver (max reconnections, can’t connect) to Unknown state as Volume state.

See https://docs.google.com/document/d/1JLli7g1Abri8O5mJkbg6lAD5CG8QLBOL60I25B1hVtc/

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/439
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.4.8
