### ISSUE TITLE
Add error for Disk safety below 0

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#459]
Currently we throw an error when disk safety is 0. We should also throw an error (different error code) when disk safety is below 0.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/468
Packaged in openvstorage-health-check_3.8.0-dev.1527510338.6c60a57-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.4.9 and https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.8.0
