### ISSUE TITLE
configure NSM load thresholds

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#473]
We would like to configure the NSM load thresholds via the Configuration (default_arguments)

```
"alba": {
        "disk-safety-test": {
            "include_errored_as_dead": false,
            "skip_backend": [],
            "backend": []
        },
        "backend-test": {},
        "processes-test": {},
        "proxy-test": {},
        "nsm-load-test": {
             "max_load": 500
         },
        "proxy-port-test": {}
    },
```

**Comment by JeffreyDevloo** [comment]
Proper implementation by https://github.com/openvstorage/openvstorage-health-check/pull/476
Packaged in openstorage-health-check_3.8.0-dev.1527679835.c3779be-1_amd64.deb

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.4.10 and https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.8.0
