### ISSUE TITLE
Noticed a few leftover entries after running OpenvSwiper.sh

### ISSUE THREAD

**Issue by pploegaert** [openvstorage/openvstorage-health-check#50]
In case a user wants to switch ip addresses in between, this might lead to issues:

on avahi level:
```avahi/services/ovs_cluster.service:6:    <name replace-wildcards="yes">ovs_cluster_preconfig-10-100-197-1_ovs04_10_100_197_4</name>```

I'd remove /etc/init/ovs-* entries completely:
```init/ovs-etcd-config.conf:25:exec etcd -proxy on -data-dir /opt/OpenvStorage/db/etcd/config/data -listen-client-urls http://127.0.0.1:2379 -initial-cluster wLWudL54FRR1kpiO=http://10.100.197.1:2380,sUxlFlQ64JzqWBRQ=http://10.100.197.3:2380,inqLfEcsdcFaPMqf=http://10.100.197.2:2380```

Optional logging can be removed too:
```beaver/beaver.conf:3:redis_url: redis://10.100.197.102:6379
statsmonkey/statsmonkey.conf:3:host: 10.100.197.104```

**Comment by kinvaris** [comment]
That is very weird, have you ran the Open vSwiper 2 times?

**Comment by pploegaert** [comment]
Wrong repo
