### ISSUE TITLE
More meaningful error message

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#68]
In case there is an issue with the volumedriver the info is quite sketchy:

> [INFO] Checking volumedrivers: 
> [FAILURE] Some volumedrivers seem to have some problems: vmstor

Please make this more clear so it at least list which voldrv are affected and if possible what the issue is.

**Comment by kinvaris** [comment]
You cannot pinpoint a certain problem to a volumedriver, this means that the healthcheck cannot yet discover what problem is occuring here. 

Currently the healthcheck gives you the name of the vpool/volumedriver that has problems. In this case
`vmstor`. 

When you run the healthcheck you get a meaningful output of the environment at the beginning, this should be included in the bug/problem report.
```
[INFO] Starting Open vStorage Health Check!
[INFO] ====================================
[INFO] Fetching LOCAL information of node: 
[SUCCESS] Cluster ID: u7GyHd2UhCRj1uET
[SUCCESS] Storagerouter ID: pqpLJt0yeVvUjfrK
[SUCCESS] Environment TYPE: MASTER
[SUCCESS] Environment VERSION: Fargo
```
