### ISSUE TITLE
Package the health check

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#71]
Currently the health check is a script which gets checked out from GitHub. We should package it so you can apt-get the correct version.

Name proposal: openvstorage-tools

**Comment by kinvaris** [comment]
I would just call it openvstorage-healthcheck because openvstorage-tools could be used for the support tools

**Comment by pploegaert** [comment]
I'd keep the pkg / repo name in sync: I'd use: openvstorage-health-check

**Comment by kinvaris** [comment]
done, you can install it as `apt-get install openvstorage-health-check`
