### ISSUE TITLE
arakoon collapsing

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#72]
Can we monitor the arakoon collapsing?
By checking the stats from head.db and the amount of tlx,tlog files?

**Comment by JeffreyDevloo** [comment]
### Steps
- Setup ovs cluster
- Ran healthcheck

### Output
The check has been added, but is a bit lack luster.
```
[SUCCESS] ALL Arakoon(s) are collapsed.
```

### Test result
Test passed,

### Information
https://github.com/openvstorage/openvstorage-health-check/pull/120 adds more output.
