### ISSUE TITLE
Autotests regression testing

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#73]
Todo tests: (Throwing exceptions to check if fixed in healthcheck, this created from previous bugs)
- https://github.com/openvstorage/openvstorage-health-check/issues/23, throw an ObjectNotFoundException during check halted volumes
- https://github.com/openvstorage/openvstorage-health-check/issues/18, delete a vdisk from ovsdb and check if it is reported in the healthcheck
- https://github.com/openvstorage/openvstorage-health-check/issues/25, vpool is not present on a node so skip that test
- https://github.com/openvstorage/openvstorage-health-check/issues/26, throw a MaxRedirectsExceededException when querying a volume for volumeInfo
- https://github.com/openvstorage/openvstorage-health-check/issues/29, throw ClusterNotReachableException when Checking model consistency
- https://github.com/openvstorage/openvstorage-health-check/issues/30, delete a directory that has needs to be checked. To check if OSError: [Errno 2] No such file or directory does not occur
- https://github.com/openvstorage/openvstorage-health-check/issues/33, shutdown ETCD with so it cannot fetch ETCD configs.
- https://github.com/openvstorage/openvstorage-health-check/issues/36, Check for ImportError(s)
- https://github.com/openvstorage/openvstorage-health-check/issues/60, cause arakoon to fail so MasterLookupResult.Error occurs.
- https://github.com/openvstorage/openvstorage-health-check/issues/54, check if the required log files are checked by the healthcheck
- Check if a service who is down is marked as failed.
- Check a port who is down is marked as down.

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/integrationtests/commit/2b70a80eaaec6b1430486bf0fdaebc7d4d317cb2
