### ISSUE TITLE
Check if an ovs process is multiple restarted in x minutes

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#78]
Check if an ovs process is multiple restarted in x minutes.
Like we do with Arakoon. [_check_restarts](https://github.com/openvstorage/openvstorage-health-check/blob/8c80de211470a8d951c95e07584916264abb0cdf/ovs/extensions/healthcheck/arakoon/arakooncluster_health_check.py#L168)
Maybe reuse this method and use this as an (utils) extension method?

**Comment by JeffreyDevloo** [comment]
In short a method is requested to parse log files for multiple restart calls within a certain timeframe.

**Comment by JeffreyDevloo** [comment]
After checking with @jeroenmaelbrancke this check would require too much resource for the healthcheck and should frankly be monitored by Ops.
