### ISSUE TITLE
Namespace is created for every preset but never deleted.

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#85]
In continuation of: https://github.com/openvstorage/openvstorage-health-check/issues/62

This gives indeed problems: you cannot delete the presets anymore because leftover namespaces are still available in the backend, garbage in the backend, ...

**Comment by wimpers** [comment]
@kinvaris What do you suggest?  What do you really want to test/verify.

**Comment by JeffreyDevloo** [comment]
Just checked with @khenderick to check what is stored in the DAL to which he replied that neither the presets nor the namespaces are stored within the DAL.
These values are simply fetched from alba and cached.

Deleting the namespace that healthcheck creates and then the preset should resolve the issue.

**Comment by JeffreyDevloo** [comment]
Waiting on https://github.com/openvstorage/alba/issues/427 to merge the deletion.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/264
