### ISSUE TITLE
Rework code/structure healthcheck - upgrade to arakoon

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#94]
Refactor structure/code from healthcheck

**Comment by kinvaris** [comment]
https://github.com/openvstorage/openvstorage-health-check/blob/master/ovs/lib/healthcheck.py#L145
shadows module name

**Comment by kinvaris** [comment]
@khenderick & @kvanhijf if you have some time you are always welcome to point out mistakes, ...

**Comment by kinvaris** [comment]
https://github.com/openvstorage/openvstorage-health-check/issues/98

**Comment by JeffreyDevloo** [comment]
Using Configuration from Framework to support both ETCD and Arakoon.

**Comment by JeffreyDevloo** [comment]
### Steps
- Installed a cluster with etcd
- Ran healthcheck

- Installed cluster with arakoon
- Ran healthcheck

### Output
Healthcheck completed in both cases

### Test result
Test passed.
