### ISSUE TITLE
integrate tcp connections of arakoon check in healthchec

### ISSUE THREAD

**Issue by grimpy** [openvstorage/openvstorage-health-check#95]
Last week we had a meeting and was told you have a check in check mk that does this. can this be integrated in the healtcheck? 

Note fromt meeting:

```
amount of TCP connections to arakoon (arakoons still running / GUI not accessible since amount of TCP session too high) - thresholds (arakoon github has default values)
```

**Comment by wimpers** [comment]
I believe the check was added in check_mk because of 
https://github.com/openvstorage/framework-alba-plugin/issues/322

@jeroenmaelbrancke can you confirm:
* we no longer  see the issue (Arakoon running out of fd)
* we no longer are using this check in check_mk

**Comment by jeroenmaelbrancke** [comment]
@wimpers:
We still have the filedescriptor and thread check in checkmk but we will migrate this to grafana as we no longer want alerts about this.

see ticket: https://github.com/openvstorage/operations/issues/14

**Comment by wimpers** [comment]
If we want to integrate into the healthcheck we need to: 
* Define threshold levels for warning and alert
* Decide whether we track established connections or listening or both.

**Comment by simonOpenV** [comment]
initial working test commited to branch arakoon_tcp_connections
note that a branch is made for this on framework extensions as well: add_fd, to retrieve the file descriptors

**Comment by saelbrec** [comment]
I think it's still good to have this monitoring.
The thresholds need be set to 80% and 95% of the configured fd limit.

We should also take all connections into account (ESTABLISHED & TIME_WAIT)

**Comment by simonOpenV** [comment]
https://github.com/openvstorage/framework-extensions/pull/61
https://github.com/openvstorage/openvstorage-health-check/pull/400

**Comment by JeffreyDevloo** [comment]
Part of the next 3.4 release which modifies the one from Simon and adds external arakoon support to it

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.6.2
