### ISSUE TITLE
df: ‘/mnt/geo-accelerated-alba’: Transport endpoint is not connected

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#99]
Add monitoring for (replace the vpool name)

df: ‘/mnt/geo-accelerated-alba’: Transport endpoint is not connected

As it indicates something went wrong with the volumedriver for that vpool and it will prevent it from being restarted as well.

ticket [79](https://github.com/openvstorage/openvstorage-monitoring/issues/79)

**Comment by wimpers** [comment]
Is this something which gets logged in a log? If so better use the central log monitoring instead of grepping the log sin the health check.

**Comment by JeffreyDevloo** [comment]
The FUSE test should indicate this problem.
@wimpers It is a message  you receive when trying to enter the volumedriver directory when its not running
